---
- name: Converge
  hosts: all

  tasks:
    - name: Update apt cache (on Debian).
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

- ansible.builtin.import_playbook: ../../main.yml
