# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "geerlingguy/ubuntu2004"
  config.vm.network :private_network, ip: "192.168.56.8"
  config.vm.hostname = "galaxy-role-servers.test"
  config.ssh.insert_key = false

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
  end

  # Ansible provisioning.
  config.vm.provision "lamp", type:'ansible' do |ansible|
    ansible.playbook = "lamp.yml"
  end
  config.vm.provision "solr", type:'ansible' do |ansible|
    ansible.playbook = "solr.yml"
  end
end
