---
- hosts: k8s-master
  become: yes

  pre_tasks:
    - name: Ensure ansible version is supported.
      assert:
        that: "ansible_version.full is version_compare('2.7', '>=')"
        msg: >
          "Minimum ansible version for this playbook is 2.7"
          "Minimum tested is 2.7.9"

    - name: Ensure Pip is installed.
      package:
        name: python-pip
        state: present

    - name: Ensure OpenShift client is installed.
      pip:
        name: openshift
        state: present

  tasks:
    - name: Apply Nginx definition from Ansible controller file system.
      k8s:
        state: present
        definition: "{{ lookup('file', 'files/nginx.yml') | from_yaml }}"

    - name: Expose the Nginx service with an inline Service definition.
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            labels:
              app: nginx
            name: a4d-nginx
            namespace: default
          spec:
            type: NodePort
            ports:
            - port: 80
              protocol: TCP
              targetPort: 80
            selector:
              app: nginx

    - include_tasks: files/k8s_info.yml
      when: "ansible_version.full is version_compare('2.9', '>=')"

    - include_tasks: files/k8s_facts.yml
      when: "ansible_version.full is version_compare('2.9', '<')"

    - name: Print the NodePort of the a4d-nginx Service.
      debug:
        var: a4d_nginx_service.resources[0].spec.ports[0].nodePort
