---
# Handler to handle DB tier notifications
# if any error happend here we should start mariadb manually with: systemctl start mariadb.service
# not root privilege may cuz error

- name: restart mariadb
  service: name=mariadb state=restarted
  ignore_errors: true

